### ISSUE TITLE
9/24 동현 todo

### ISSUE THREAD

**Issue by dooking** [TEAM-BIDI/bidi#113]
## 📑 체크리스트
- [x] 위치 모듈 구현 (쿠팡이츠, 배달의 민족 디자인 참고)
- [x] 비드 작성, 수정에 스타일 메뉴 기능 추가
- [x] 스타일 수정 서버 코드 추가
- [x] 유저 버젼에서 디자이너 헤어샵 정보 추가
- [x] 개인정보 취급 url 논의
- [x] 맥북 <-> 아이폰 연결 시도
