### ISSUE TITLE
bid 작성 관련 todo list

### ISSUE THREAD

**Issue by dooking** [TEAM-BIDI/bidi#33]
## 💁 목표
- bid 작성 (디자이너 ver 첫 번째 탭) 스크린의 추가할 기능을 정리해본다.

## 📑 체크리스트
- [x] Carousel 관련 다른 라이브러리가 있는지 찾아보기
- [x] 찜하기 버튼 구현 (우선순위 하)
- [x] 비드 작성하기 버튼 구현 (위치 수정)
- [ ] 비드 작성 시, bottom tab이 보이지 않아야 함
- [x] 희망 예산 데이터를 범위로 바꿔주기 (10000 -> **5000 ~ 10000**) 
- [x] 드롭 다운 완성하기 (대분류 선택에 따라 소분류가 변경되어야함)
- [ ] 스타일북 페이지 작성
- [x] biid 관련 API 구현
