### ISSUE TITLE
[User-FirstTap] 디자이너 스와이프 / 스타일 세부페이지 Todo List

### ISSUE THREAD

**Issue by longshiine** [TEAM-BIDI/bidi#45]
## 💁 목표
- 디자이너 스와이프 스크린 디자인 수정 
- 스타일 세부페이지 구현 

## 📑 체크리스트
- [x] 디자이너 포트폴리오 카드 디자인
- [x] 이 디자이너의 스타일 디자인
- [x] 매칭 히스토리 디자인
- [x] 스타일 Detail 페이지 구현
