### ISSUE TITLE
[User-FourthTab] 매칭 히스토리 / 스타일 스크랩 Todo List

### ISSUE THREAD

**Issue by longshiine** [TEAM-BIDI/bidi#46]
## 💁 목표
- 매칭 히스토리 기능을 개발
- 스타일 스크랩에서 개별 스타일을 확인할 수 있는 스크린 제작

## 📑 체크리스트
- [x] History Schema 개발
- [x] History API 개발
- [x] 매칭 히스토리 스크린 개발
- [x] 스타일 스크랩 상세 스크린 개발

**Comment by dooking** [comment]
@longshiine 
매칭히스토리 API 명세서 업데이트 해주세요~~

**Comment by longshiine** [comment]
넵 알겠습니다~~
