### ISSUE TITLE
DM 화면(detail) TODO list

### ISSUE THREAD

**Issue by staycozyboy** [TEAM-BIDI/bidi#47]
## 💁 목표
DM 화면(detail)의 화면 구조를 설계하고, 디자인 입히기

## 📑 체크리스트
- [x] Navigation 연결
- [x] 헤더 바 커스터마이징
  - [ ] 디자이너 브랜딩 페이지로 navigate
- [x] 채팅 스크롤 뷰
  - [ ] 스크롤할 수 없을 때는 위에서 부터 렌더링
  - [ ] 스크롤 가능시 아래에서부터 거꾸로 렌더링
    - [ ] Infinite Scroll 
  - [x] 채팅 말풍선 스타일
    - [ ] 텍스트 뿐만 아니라 이미지 또한 처리 가능하도록
  - [ ] 날짜에 따라 grouping
  - [x] 가장 마지막에 확인한 메세지와 작은 프로필 이미지 뱃지 일치하도록
- [x] 메세지 입력 바
  - [ ] 카메라
  - [ ] 앨범에서 가져오기
 
## 🙌 실행 화면
![simulator_screenshot_525151D6-5F37-4D4F-BAED-B1B12E905F23](https://user-images.githubusercontent.com/37537248/128612899-42b704e7-acd7-4368-bc8d-99a814309d8f.png)
