### ISSUE TITLE
[User-ThirdTab] 제안서 작성 스크린 Todo List

### ISSUE THREAD

**Issue by longshiine** [TEAM-BIDI/bidi#48]
## 💁 목표
- after image 사진 앨범에서 가져오기 스크린 구현
- after image 스크랩북에서 가져오기 스크린 구현
- 제안서 작성 구체화

## 📑 체크리스트
- [x] after image 사진 앨범에서 가져오기 구현
- [x] after image 스크랩 북에서 가져오기 구현
- [ ] 요청 사항 관련 업데이트
- [ ] 위치 계산 어떤식으로 할지 solve
