### ISSUE TITLE
[User-SecondTab] 내 제안서 / 받은 비드 Todo-List

### ISSUE THREAD

**Issue by longshiine** [TEAM-BIDI/bidi#50]
## 💁 목표
- 내 제안서 / 받은 비드 구현

## 📑 체크리스트
- [x] 디자인 완성
- [x] 내 제안서 수정하기 after 사진 수정 구현
- [ ] 내 제안서 수정하기 드롭박스 기존 데이터 불러오기
- [x] 받은 비드 거절하기 / 수락하기 API 연동
