### ISSUE TITLE
[DM] DM 관련 BE TODO list

### ISSUE THREAD

**Issue by staycozyboy** [TEAM-BIDI/bidi#63]
## 💁 목표
DM 관련 BE 설정까지 완료
기능에 따라 incremental하게 구현하자

일단 가장 기본적인 채팅 기능부터
1. 유저 - 디자이너 간 비드 기반으로 DM 가능
2. Realtime으로 메세지를 주고받을 수 있다
3. 확인하지않은 채팅방 마킹 (유저, 디자이너)
4. 메세지를 확인하지 않고, 채팅방 리스트 뷰에서 가장 최근 메세지 볼 수 있음
5. 확인하지않은 메세지가 존재하는 채팅방 마킹 (유저, 디자이너)

## 📑 체크리스트
- 가장 기본적인 채팅 기능
  - [x] 관련 DB 수정 (entity 추가)
  - [x] User - DM 연결
  - [ ] Bid의 status가 진행중으로 바뀔 때, room create하도록 설정
  - [x] socket.io handshake query? -> Slack 채널, 이모지 코드 참고확인하기
    - [ ] DM List 에서 userID로 handshake -> Joining ALL Rooms
  - [ ] 채팅방 스크롤 설정 (FE)
  - [ ] 안읽음에 대한 marker 조건부 렌더링 (FE)
  - [ ] 더 있나..?
---
- JWT 인증 middleware 설정
- 유저 소속은 어떻게 처리할 것인지
- DM 디자이너 헤더 누르면 개인 브랜딩 페이지 / DM 유저 헤더는 누르면 어떻게 할까
- 디자이너 인증완료 패치
  - user schema 수정
  - FE 수정
- 채팅방 검색 기능
- 메세지: 사진 보내기 기능
  - Camera / Image Picker
  - message schema 수정
