### ISSUE TITLE
[DM] 온전한 채팅 앱 구현 TODO list

### ISSUE THREAD

**Issue by staycozyboy** [TEAM-BIDI/bidi#78]
## 💁 목표
BiDi Messenger 구현하기 = 깔끔한 채팅 앱 완성

## 📑 체크리스트
- DB 구조 변경
  - [ ] room entitiy가 bid와 1:1 관계가 아닌 matching과 1:1 관계를 가지도록
  - [ ] Message가 사진 등의 다양한 content를 담을 수 있도록 message와 1:1 관계를 가지는 content entity 설계 및 추가
- [ ] socket 통신 시 웹 토큰으로 인증하도록 middleware 설정
- [ ] socket 통신 CORS 설정 확인하기 
- 각종 필수 기능
  - [ ] 새 매치 -> 확인/미확인 설정
  - [ ] 새 메세지 -> 읽음/안읽음 설정
  - [ ] 채팅방 삭제기능(only 매칭이 완료된 경우)
  - [ ] 디자이너 - 소속 / 유저 - 주소 표기
    - Q. 1대 1 DM 화면에서 헤더를 누를 시 어디로 navigate? 디자이너의 경우 브랜딩 페이지로 넘어가는 것이 자연스러움, 허나 유저는? 제안서 상세?
    - 그리고 저쪽으로 navigate하는 것 되는지 확인
  - [ ] 채팅방 검색 기능 -> 간단한 라이브러리 탐색
  - [ ] 디자이너 인증완료 표기
- FE 부족한 부분 채우기
  - [ ] 비슷한 시간대별로 메세지 그룹화 -> 레퍼런스가 있을까? (카카오 테크 블로그 등 참고)
  - [ ] 가장 최근 메세지 글자 수 고려 표시 제한 -> [... + 보낸 시간]으로 표기
  - [ ] 매치가 아예 없는 경우 표기
  - 메세지 textinput 관련
    - [ ] 줄바꿈 깔끔하게
    - [ ] 필요한 버튼UI 추가
- 메세지 컨텐츠 관련 (일단 text or photo까지만만 가능)
  - [ ] 슬라이더/모달 띄우기
  - [ ] 카메라/Image Picker 연결
  - [ ] 사진포함한 chatbubble component 구현
- 푸쉬 알림 기능 -> 일단 슬랙 프로젝트 확인 + 레퍼런스 탐색

## 🚧 주의 사항
- 추후 리팩토링시 부담을 줄이기 위해 컴포넌트 구조, 변수명, 클린 코드에 더 신경 쓰기
